# Generated by Django 3.1.3 on 2020-11-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='api key of youtube API', max_length=200)),
                ('quota_available', models.BooleanField(default=True, help_text='check whether quota is finished, update to false')),
                ('last_status_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='video title', max_length=200)),
                ('youtube_id', models.CharField(help_text='videoId', max_length=20)),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
