# Generated by Django 3.1.3 on 2020-11-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIKeys',
            new_name='APIKey',
        ),
    ]
