# Generated by Django 3.1.3 on 2020-11-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0002_auto_20201118_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(help_text='videoId', max_length=20, unique=True),
        ),
    ]
