# Generated by Django 3.1.3 on 2020-11-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0003_auto_20201118_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_index=True, help_text='video title', max_length=200),
        ),
    ]
