# Generated by Django 3.1.3 on 2020-11-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0004_auto_20201118_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='published_date',
            new_name='published_at',
        ),
    ]
