# Generated by Django 3.1.3 on 2020-11-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0005_auto_20201118_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='last_status_updated',
            new_name='last_used',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(help_text='api key of youtube API', max_length=200, unique=True),
        ),
    ]
