# Generated by Django 3.1.3 on 2020-11-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0006_auto_20201118_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainingJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_token', models.CharField(help_text='storing next page token so we can continue with the paginated results', max_length=20, unique=True)),
                ('lower_date_bound', models.DateTimeField(help_text='storing the lower bound of date so that i can filter using after query')),
                ('upper_date_bound', models.DateTimeField(help_text='storing upper bound so we know that our list is between the bounds')),
            ],
        ),
    ]
