# Generated by Django 3.1.3 on 2020-11-19 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0009_auto_20201119_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
