# Generated by Django 3.1.3 on 2020-12-02 18:33

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0011_auto_20201202_1816'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='remainingjobs',
            name='check valid boundaries',
        ),
        migrations.AddConstraint(
            model_name='remainingjobs',
            constraint=models.CheckConstraint(check=models.Q(upper_date_bound__gt=django.db.models.expressions.F('lower_date_bound')), name='check valid boundaries'),
        ),
    ]
