version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7.4

        steps:
            - checkout
            # - restore_cache:
            #     key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run:
                name: installing project dependencies
                command: |
                    pip3 install virtualenv
                    virtualenv -p python3.7 venv
                    source venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
            # - save_cache:
            #     key: 
            #         - deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
            #     paths:
            #         -"venv"
            - run:
                name: running tests..
                command: |
                    python manage.py test
            - store_artifacts:
                path: test-reports/
                destination: YoutubeArchives

workflow:
    build_and_run_tests:
        jobs:
            - build